name: Docker Build and Push
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and push to GHCR (multi-arch)
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set TAG
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Enable QEMU (binfmt)
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Setup Docker buildx
        run: docker buildx create --use

      - name: Run Docker buildx
        run: |
          OWNER_LC="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BITCOINABC_VERSION=0.32.7 \
            --tag ghcr.io/${OWNER_LC}/xecd-abc:${{ env.TAG }} \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .
